# CCTNS Copilot Engine - AI Models Configuration
# This file contains configuration for all AI/ML models used in the system

# Model Cache and Storage
model_storage:
  cache_dir: "./models_cache"
  max_cache_size_gb: 50
  auto_cleanup: true
  cleanup_threshold_days: 30

# Hardware Configuration
hardware:
  use_gpu: true
  gpu_memory_fraction: 0.8
  cpu_cores: -1  # Use all available cores
  mixed_precision: true

# Speech-to-Text Models
speech_to_text:
  primary:
    name: "ai4bharat/indicconformer"
    model_type: "wav2vec2"
    language_support: ["te", "hi", "en-IN"]
    confidence_threshold: 0.7
    device: "auto"  # auto-detect GPU/CPU
    batch_size: 1
    sample_rate: 16000
    max_audio_length: 300  # seconds
    preprocessing:
      normalize_audio: true
      remove_silence: true
      noise_reduction: true
    
  fallback:
    name: "openai/whisper-medium"
    model_type: "whisper"
    language_support: ["te", "hi", "en", "auto"]
    confidence_threshold: 0.6
    device: "auto"
    temperature: 0.0
    beam_size: 5
    best_of: 5
    
  # Language-specific models
  language_models:
    telugu:
      primary: "ai4bharat/indicconformer_te"
      fallback: "openai/whisper-medium"
    hindi:
      primary: "ai4bharat/indicconformer_hi" 
      fallback: "openai/whisper-medium"
    english:
      primary: "openai/whisper-medium"
      fallback: "wav2vec2-base-960h"

# Text Processing Models
text_processing:
  grammar_correction:
    name: "google/flan-t5-base"
    temperature: 0.3
    max_length: 200
    min_length: 10
    num_beams: 4
    early_stopping: true
    
  enhancement:
    name: "microsoft/DialoGPT-medium"
    temperature: 0.1
    max_length: 100
    top_p: 0.9
    repetition_penalty: 1.1
    
  language_detection:
    name: "facebook/fasttext-langdetect"
    confidence_threshold: 0.8
    supported_languages: ["te", "hi", "en"]
    
  translation:
    english_to_telugu:
      name: "ai4bharat/indictrans2-en-indic"
      beam_size: 4
      temperature: 0.0
    telugu_to_english:
      name: "ai4bharat/indictrans2-indic-en"
      beam_size: 4
      temperature: 0.0

# Natural Language to SQL Models
nl2sql:
  primary:
    name: "microsoft/CodeT5-base"
    model_type: "code_generation"
    temperature: 0.1
    max_length: 300
    min_length: 20
    beam_size: 5
    early_stopping: true
    
  fallback:
    name: "rule_based"
    confidence_threshold: 0.8
    template_matching: true
    
  preprocessing:
    normalize_entities: true
    expand_abbreviations: true
    correct_spelling: true
    
  postprocessing:
    validate_syntax: true
    sanitize_queries: true
    add_limits: true
    max_result_rows: 1000

# Text Summarization Models
summarization:
  report_summary:
    name: "google/pegasus-cnn_dailymail"
    max_length: 150
    min_length: 30
    num_beams: 4
    temperature: 0.7
    length_penalty: 2.0
    
  query_summary:
    name: "facebook/bart-large-cnn"
    max_length: 100
    min_length: 20
    num_beams: 3
    temperature: 0.5

# Named Entity Recognition
ner:
  police_entities:
    name: "custom/police-ner-model"
    entities: ["PERSON", "LOCATION", "CRIME_TYPE", "DATE", "STATION", "DISTRICT"]
    confidence_threshold: 0.8
    
  general_entities:
    name: "dbmdz/bert-large-cased-finetuned-conll03-english"
    entities: ["PER", "LOC", "ORG", "MISC"]

# Embeddings and Similarity
embeddings:
  sentence_embeddings:
    name: "sentence-transformers/all-MiniLM-L6-v2"
    dimension: 384
    
  query_similarity:
    name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    threshold: 0.7

# CCTNS Database Schema Configuration
cctns_schema:
  database_type: "oracle"
  schema_version: "2.0"
  
  tables:
    # Master Tables
    - name: "M_STATE"
      type: "master"
      columns: ["state_cd", "lang_cd", "state", "official_lang_cd", "record_status", "last_updated_on", "state_veh_reg_cd"]
      primary_key: "state_cd"
      description: "Stores master information about Indian States."
    - name: "M_DISTRICT"
      type: "master"
      columns: ["district_cd", "lang_cd", "state_cd", "district", "record_status", "last_updated_on", "dist_short_form"]
      primary_key: "district_cd"
      foreign_keys:
        - column: "state_cd"
          references: "M_STATE.state_cd"
      description: "Stores master information about Districts within States."
    - name: "M_POLICE_UNITS"
      type: "master"
      columns: ["unit_cd", "lang_cd", "state_cd", "district_cd", "unit_name", "unit_type_cd", "record_status", "latitude", "longitude", "locality", "street_road_no", "pincode"]
      primary_key: "unit_cd"
      foreign_keys:
        - column: "state_cd"
          references: "M_STATE.state_cd"
        - column: "district_cd"
          references: "M_DISTRICT.district_cd"
      description: "Contains master data about police units (stations, offices) within the districts."
    - name: "M_CRIME_CLASS"
      type: "master"
      columns: ["crime_class_cd", "lang_cd", "crime_class", "record_status", "last_updated_on"]
      primary_key: "crime_class_cd"
      description: "Stores crime classification master details (e.g., Bodily Offence, Crime against Women)."
    - name: "M_MAJOR_HEAD"
      type: "master"
      columns: ["major_head_code", "lang_cd", "major_head", "record_status", "last_updated_on"]
      primary_key: "major_head_code"
      description: "Stores master data about major heads of crime (e.g., Murder For Gain)."
    - name: "M_MINOR_HEAD"
      type: "master"
      columns: ["minor_head_cd", "lang_cd", "major_head_code", "minor_head", "record_status", "last_updated_on"]
      primary_key: "minor_head_cd"
      foreign_keys:
        - column: "major_head_code"
          references: "M_MAJOR_HEAD.major_head_code"
      description: "Stores master data about minor heads linked to major heads (e.g., Attempt To Commit under a major head)."
    - name: "M_ACT"
      type: "master"
      columns: ["act_cd", "lang_cd", "act_long", "act_short", "record_status", "last_updated_on", "amendment_year"]
      primary_key: "act_cd"
      description: "Stores master information about Acts (e.g., THE BHARATIYA NYAYA SANHITA (BNS), 2023)."
    - name: "M_SECTION"
      type: "master"
      columns: ["section_cd", "lang_cd", "section_code", "act_sec_cd", "section", "short_desc", "description", "offence", "punishment", "isvalid", "ispunishable", "isbailable", "iscognizable", "isgrave", "record_status", "last_updated_on"]
      primary_key: "section_cd"
      foreign_keys:
        - column: "act_sec_cd" # This column in M_SECTION refers to act_cd in M_ACT
          references: "M_ACT.act_cd"
      description: "Stores master information about law sections under various Acts."
    - name: "M_PERSON_TYPES"
      type: "master"
      columns: ["person_type_cd", "lang_cd", "person_type", "record_status", "last_updated_on", "is_req_for_cis"]
      primary_key: "person_type_cd"
      description: "Stores master information about person types (e.g., Complainant, Accused, Victim)."
    - name: "M_MASTER_DATA" # Generic master table for various codes
      type: "master"
      columns: ["master_cd", "master_type_cd", "master_parent_cd", "lang_cd", "master_value", "is_active", "cas_master_cd", "record_status", "last_updated_on"]
      primary_key: "master_cd"
      description: "Generic master table for configurable data (e.g., Gender, Nationality, Occupation, FIR Status, Grave Type codes and their values)."

    # Transaction Tables
    - name: "T_FIR_REGISTRATION"
      type: "transaction"
      columns: ["fir_reg_num", "petition_id", "lang_cd", "state_cd", "district_cd", "ps_cd", "fir_srno", "reg_year", "reg_dt", "fir_action", "gd_num", "gd_entry_dt", "crime_class_cd", "oth_crime_class", "grave_type_cd", "nature_of_offence", "prop_involve_or_not_chk", "no_accused_chk", "unknown_accused_chk", "compl_src", "inform_type", "inform_recv_dt", "delay_reason_compl", "persons_dead_count", "seriously_hurt_count", "simply_hurt_count", "property_value", "action_taken_cd", "assigned_io_cd", "fir_status", "is_fir_secret", "fir_reg_officer_cd", "record_status", "record_created_on", "fir_contents", "brief_facts_lang", "victim_flg_check", "no_of_victims_entrd", "irad_accdnt_id"]
      primary_key: "fir_reg_num"
      foreign_keys:
        - column: "state_cd"
          references: "M_STATE.state_cd"
        - column: "district_cd"
          references: "M_DISTRICT.district_cd"
        - column: "ps_cd"
          references: "M_POLICE_UNITS.unit_cd"
        - column: "crime_class_cd"
          references: "M_CRIME_CLASS.crime_class_cd"
        - column: "grave_type_cd" # Refers to M_MASTER_DATA where master_type_cd might be for grave types
          references: "M_MASTER_DATA.master_cd"
        - column: "fir_status" # Refers to M_MASTER_DATA where master_type_cd might be for FIR statuses
          references: "M_MASTER_DATA.master_cd"
      description: "Primary table for FIR Registration, containing all metadata related to registered FIRs."
    - name: "T_FIR_ACT_SECTION"
      type: "transaction"
      columns: ["fir_act_srno", "lang_cd", "fir_reg_num", "act_cd", "section_cd", "read_with_flg", "fir_alter_status", "record_status", "record_created_on", "module_name", "operation_flag"]
      primary_key: "fir_act_srno" # DDL mentions (LANG_CD, FIR_ACT_SRNO) as PK but schema explanation implies FIR_ACT_SRNO
      foreign_keys:
        - column: "fir_reg_num"
          references: "T_FIR_REGISTRATION.fir_reg_num"
        - column: "act_cd"
          references: "M_ACT.act_cd"
        - column: "section_cd"
          references: "M_SECTION.section_cd"
      description: "Links FIRs to relevant legal Acts and Sections applied."
    - name: "T_FIR_MAJOR_MINOR_HEADS"
      type: "transaction"
      columns: ["fir_mjmn_srno", "lang_cd", "fir_reg_num", "major_head_code", "oth_major_head", "minor_head_cd", "fir_alter_status", "record_status", "is_major_primary_chk", "operation_flag"]
      primary_key: "fir_mjmn_srno"
      foreign_keys:
        - column: "fir_reg_num"
          references: "T_FIR_REGISTRATION.fir_reg_num"
        - column: "major_head_code"
          references: "M_MAJOR_HEAD.major_head_code"
        - column: "minor_head_cd"
          references: "M_MINOR_HEAD.minor_head_cd"
      description: "Links FIRs to relevant crime major and minor heads."
    - name: "T_PERSON_INFO"
      type: "transaction" # Can be considered a core entity, but often involved in transactions
      columns: ["person_code", "lang_cd", "person_type_cd", "reg_year", "first_name", "middle_name", "last_name", "dob", "age", "father_name", "relation_type_cd", "occupation_cd", "gender_cd", "caste_tribe_cd", "religion_cd", "nationality_cd", "edu_qual_cd", "mobile_1", "email", "injury_type_cd", "state_cd", "district_cd", "ps_cd", "full_name", "living_status_cd", "marital_status_cd", "record_status", "is_known", "alias_name", "fir_num", "bank_acc_num"]
      primary_key: "person_code"
      foreign_keys:
        - column: "person_type_cd"
          references: "M_PERSON_TYPES.person_type_cd"
        - column: "occupation_cd" # Refers to M_MASTER_DATA
          references: "M_MASTER_DATA.master_cd"
        - column: "gender_cd" # Refers to M_MASTER_DATA
          references: "M_MASTER_DATA.master_cd"
        - column: "nationality_cd" # Refers to M_MASTER_DATA
          references: "M_MASTER_DATA.master_cd"
        - column: "edu_qual_cd" # Refers to M_MASTER_DATA
          references: "M_MASTER_DATA.master_cd"
        - column: "state_cd"
          references: "M_STATE.state_cd"
        - column: "district_cd"
          references: "M_DISTRICT.district_cd"
        - column: "ps_cd"
          references: "M_POLICE_UNITS.unit_cd"
        - column: "fir_num" # Link to specific FIR
          references: "T_FIR_REGISTRATION.fir_reg_num"
      description: "Captures comprehensive details of persons involved in FIRs (victims, accused, complainants, etc.)."
    - name: "T_FIR_COMPLAINANT_INFO"
      type: "transaction"
      columns: ["compl_srno", "fir_reg_num", "lang_cd", "time_delay_cd", "person_code", "victim_complainant_chk", "record_status"] # Assuming compl_srno from explanation
      primary_key: "compl_srno" # Based on schema explanation, not directly in DDL as PK
      foreign_keys:
        - column: "fir_reg_num"
          references: "T_FIR_REGISTRATION.fir_reg_num"
        - column: "person_code"
          references: "T_PERSON_INFO.person_code"
      description: "Captures details of complainants linked to an FIR."
    - name: "T_ACCUSED_INFO"
      type: "transaction"
      columns: ["accused_srno", "lang_cd", "fir_reg_num", "person_code", "accused_type_flg", "is_accused_police", "acc_police_cd", "yet_to_be_arrested", "accused_known", "accused_suspect", "accused_status_cd", "is_juvenile", "chrgsht_or_not", "record_status", "arrest_surrend", "photo"]
      primary_key: "accused_srno"
      foreign_keys:
        - column: "fir_reg_num"
          references: "T_FIR_REGISTRATION.fir_reg_num"
        - column: "person_code"
          references: "T_PERSON_INFO.person_code"
      description: "Contains detailed information about the accused individuals involved in FIRs."

# Police Terminology and Corrections
police_terminology:
  abbreviations:
    "fir": "FIR"
    "sho": "SHO"
    "asi": "ASI"
    "si": "SI"
    "ci": "CI"
    "sp": "SP"
    "ig": "IG"
    "dgp": "DGP"
    
  corrections:
    "station house officer": "SHO"
    "assistant sub inspector": "ASI"
    "sub inspector": "SI"
    "circle inspector": "CI"
    "superintendent of police": "SP"
    "inspector general": "IG"
    "director general of police": "DGP"
    
  districts:
    andhra_pradesh:
      - "Guntur"
      - "Vijayawada"
      - "Visakhapatnam"
      - "Tirupati"
      - "Kurnool"
      - "Nellore"
      - "Kadapa"
      - "Chittoor"
      - "Krishna"
      - "West Godavari"
      - "East Godavari"
      - "Srikakulam"
      - "Vizianagaram"
      - "Anantapur"
      - "Prakasam"
      
  crime_types:
    - "Murder"
    - "Theft"
    - "Robbery"
    - "Burglary"
    - "Assault"
    - "Rape"
    - "Kidnapping"
    - "Fraud"
    - "Cybercrime"
    - "Drug Trafficking"
    - "Domestic Violence"
    - "Traffic Violation"

# Query Processing Configuration
query_processing:
  max_query_length: 500
  timeout_seconds: 30
  max_results: 1000
  enable_query_caching: true
  cache_ttl_minutes: 60
  
  # Query validation rules
  allowed_operations: ["SELECT"]
  blocked_keywords: ["DROP", "DELETE", "UPDATE", "INSERT", "TRUNCATE", "ALTER"]
  
  # Result formatting
  date_format: "DD-MM-YYYY"
  number_format: "indian"
  include_metadata: true

# Logging Configuration for Models
logging:
  model_performance: true
  query_logging: true
  error_tracking: true
  metrics_collection: true
  
  log_levels:
    speech_to_text: "INFO"
    nl2sql: "DEBUG"
    database: "INFO"
    api: "INFO"

# Performance Monitoring
performance:
  enable_metrics: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  
  thresholds:
    stt_response_time_ms: 5000
    sql_generation_time_ms: 2000
    query_execution_time_ms: 10000
    total_response_time_ms: 15000
  
  alerts:
    enable_alerts: true
    alert_endpoints: []
    error_threshold_percent: 5
    response_time_threshold_ms: 20000